
spring:
  jpa:
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/rss
    username: rss
    password: rss
    driver-class-name: com.mysql.jdbc.Driver


